version: "3"
services:
  nginx:
    image: nginx:1.15.11-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./www:/var/www/html/:rw
      - ./conf/nginx:/etc/nginx/conf.d/:rw
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  php:
    build: ./build/
    ports:
      - "127.0.0.1:9501:9501"
    volumes:
      - ./www:/var/www/html/:rw
      - ./conf/php:/usr/local/etc/php:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  # mysql:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
  #     - ./data/mysql:/var/lib/mysql/:rw
  #   restart: always
  #   networks:
  #     - default
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "123"

  # postgresql:
  #   image: postgres:alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_USER: postgres
  #     # PGDATA: /var/lib/postgresql/data/pgdata
  #     # POSTGRES_DB: db
  #     # PGDATA: /tmp
  #   volumes:
  #     - gitlab-postgresql-volume:/var/lib/postgresql:Z

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

# volumes:
#   gitlab-postgresql-volume:
#     external: true

networks:
  default:
